### ISSUE TITLE
🐛 [Bug] 테스트코드 돌아가게 하기

### ISSUE THREAD

**Issue by middlefitting** [42organization/42gg.server.dev.v2#349]
### Problem

현재 작성되어 있는 대부분의 통합 테스트는 동작하지 않습니다. 실패하는 테스트를 동작하도록 모두 개선합니다.

### Reproduction

테스트 실행시 120여개의 테스트가 실패

### Screenshot

<img width="448" alt="image" src="https://github.com/42organization/42gg.server.dev.v2/assets/76660692/a9127732-81bc-46ce-a9b6-19b3badc0838">

**Comment by Kimhan-nah** [comment]
너무 좋습니다
