### ISSUE TITLE
🔨 [Refactoring] TournamentRound enum 리팩토링

### ISSUE THREAD

**Issue by Kimhan-nah** [42organization/42gg.server.dev.v2#381]
### Description

- 현재 enum class로 사용중인 `TournamentRound` 구조가 좋지 않아서 리팩토링이 필요합니다
- `EnumMap` 활용해서 수정하면 좋을 것 같습니다

### Todo
- [ ] Interface 등 match 함수도 enum class에 추가할 수 있을지 고민해보기
- [ ] `MatchTournamentService`의 `mathGames()`에서 `players`에 대한 리팩토링도 고민하기

**Comment by AreSain** [comment]
PR 올라간 것으로 확인되어 이슈 닫겠습니다!
