### ISSUE TITLE
✨ [Feature] validation 전략 개선

### ISSUE THREAD

**Issue by middlefitting** [42organization/42gg.server.dev.v2#403]
### Description

- 현재 프로젝트 로직은 검증에 대한 책임이 일관적이지 않은 문제가 있습니다. 필드 검증에 대한 책임을 해당 인스턴스로 위임하는 것으로 코드를 개선하고, 검증을 바로바로 수행할 수 있도록 합니다.

### Todo

- [ ] 커스텀 validataion 정의
- [ ] validation aop 적용

**Comment by AYoungSn** [comment]
컨트롤러 단은 valid annotation 쓰고 있는데 다른쪽도 추가하시려는 건가요?

**Comment by middlefitting** [comment]
네 우선 엔티티와 계층간 전달되는 dto에 적용하는게 목적인데요, 생성 시점 뿐만 아니라 필드 갱신 로직에서 검증을 쉽게 넣을 수 있게 하려 합니다.
