### ISSUE TITLE
🔨 [Refactoring] yml로 토너먼트 검증, 스케줄링 시간 조정

### ISSUE THREAD

**Issue by middlefitting** [42organization/42gg.server.dev.v2#412]
### Description

원활한 테스트를 위해 yml 값을 통해 dev, main에 필요한 토너먼트 제약 조건을 조절할 수 있도록 합니다.

### Todo

- [ ] 토너먼트 스케줄링 시간 조정
- [ ] 토너먼트 생성 검증 시간 조정

**Comment by Kimhan-nah** [comment]
너무 좋습니다
