### ISSUE TITLE
🔨 [Refactoring] VARCHAR 컬럼에 대한 길이 설정 추가하기

### ISSUE THREAD

**Issue by Kimhan-nah** [42organization/42gg.server.dev.v2#457]
### Description

- 토너먼트 enum type 저장하는 필드에 현재 길이 제한 설정이 없음
- 다른 entity들도 `varchar` 필드 길이 제한 확인 후 수정

**Comment by AreSain** [comment]
PR 올라간 것으로 확인되어 이슈 닫겠습니다!
