### ISSUE TITLE
🔨 [Refactoring] 프로젝트 폴더 구조 변경

### ISSUE THREAD

**Issue by AYoungSn** [42organization/42gg.server.dev.v2#529]
### Description

Entity 클래스들이 domain 이랑 admin 에서 공통적으로 사용하는 클래스인데 domain 하위 디렉토리에 있어서 찾기 어려운 문제가 있습니다
data 패키지를 domain,  admin 이랑 같은 depth 에 위치 옮기겠습니다

### Todo

- [ ] 디렉토리 구조 변경

**Comment by Kimhan-nah** [comment]
오 너무 좋아요
