### ISSUE TITLE
✨ [Feature] 신규 기수 모집 기능 추가

### ISSUE THREAD

**Issue by AYoungSn** [42organization/42gg.server.dev.v2#540]
### Description

현재 신규 기수 모집을 위해 매번 구글 폼을 만들고 스프레드시트를 통해 유저를 관리해야 하는데, 
해당 폼 관리를 위해 해당 기수들을 관리자로 추가해야 하고, 직접 슬랙 디엠을 통해 결과를 알려야 하는 불편함 등이 있어 
recruit 시스템으로 만들어 관리하고자 합니다.

BE: @AYoungSn @wken5577 @Kimhan-nah 
FE: @yoouyeon @greatSweetMango 

### Todo

- [ ] 기획 회의
- [ ] FE - 디자인
- [ ] BE - 시스템 설계
- [ ] 개발

**Comment by AreSain** [comment]
PR 올라간 것으로 확인되어 이슈 닫겠습니다!
