### ISSUE TITLE
✨ [Feature] 공고 상세 조회 API

### ISSUE THREAD

**Issue by AYoungSn** [42organization/42gg.server.dev.v2#552]
### Description

- 공고 상세 조회 (제목, 내용, 기간, 질문 등)

### URI
`GET /recruitments/{recruit_id}`

### Status Code
- 200

### Response Body
- 공고 시작일
- 공고 종료일
- title
- contents
- generation (기수)
- form
  - question :질문지
  - input type : 주관식, 다중선택 등
  - checkList : 선택인 경우 문항들
    - id : 지원하기 API에서 check list의 id가 필요하므로 response에 포함
    - contents : 문항 내용

```
{
        startDate : 'yyyy-mm-ddThh:mm:ss`,
        endDate : 'yyyy-mm-ddThh:mm:ss`,
        title: String,
        contents: String,
        generation: String,
        form: [ {
            questionId: Number,
            question: String,
            inputType: enum, // TEXT, SINGLE_CHECK, MULTI_CHECK 등
            checkList?: [{ id: Number, contents: String} , {...}, ...]
            },
            ...
        ]

}
```

**Comment by yoouyeon** [comment]
`applicationId` 추가하기!! (지원 내역이 없으면 null)
