### ISSUE TITLE
🐛 [Bug] seaseon 로직 if 문 수정으로 인한 테스트 실패 로직 복구

### ISSUE THREAD

**Issue by SONGS4RI** [42organization/42gg.server.dev.v2#573]
### Problem

이전 Pr 에서 조건문 수정으로 인한 테케 실패로 조건문 이전으로 복구

### Reproduction

로컬에서는 돌아갔는데 액션에서는 버그가 발생

**Comment by AYoungSn** [comment]
#568 이슈 중복입니다
