### ISSUE TITLE
✨ [Feature] 알림 메세지 미리보기 API

### ISSUE THREAD

**Issue by Kimhan-nah** [42organization/42gg.server.dev.v2#581]
### Description
- 메세지에서 ${} 치환

### Request Url
 `/admin/recruitments/result/message/preview?messageType={messageType}`

### Request Param
- messageType
  - INTERVIEW : 면접 안내
  - PASS : 합격 안내
  - FAIL : 불합격 안내

### Request Body

```
   {
      content : String
   }
```

**Comment by parksangmin1543** [comment]
messageType이 어떻게 될까요?
