### ISSUE TITLE
🔨 [Refactoring] recruitement 관련 엔티티 연관관계 수정

### ISSUE THREAD

**Issue by Kimhan-nah** [42organization/42gg.server.dev.v2#736]
### Description

- 기존 다대일 단방향 -> 다대일 양방향으로 수정
- Recruitments -> Recruitment로 수정 (flyway 함께 수정)

### Todo

- [ ] todo1

**Comment by AreSain** [comment]
PR 올라간 것으로 확인되어 이슈 닫겠습니다!
