### ISSUE TITLE
✨ [Feature] Readme AWS 업데이트

### ISSUE THREAD

**Issue by wken5577** [42organization/42gg.server.dev.v2#837]
### Description

- 현재 AWS ASG를 사용하는 쪽으로 수정되었고 VPC Endpoint는 사용하고 있지 않습니다
- 이를 반영하여 AWS 다이어그램 수정하겠습니다

**Comment by AreSain** [comment]
8기 작업 완료하며 README 업데이트 했습니다. 이슈 닫겠습니다!
